plugins {
    id 'com.android.application'
}

android {
    namespace 'br.edu.ifpr.quizsi'
    compileSdk 36
    buildToolsVersion '35.0.0'

    defaultConfig {
        applicationId 'br.edu.ifpr.quizsi'
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName '1.0.0'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    lint {
        abortOnError true
        checkReleaseBuilds true
    }
}

dependencies {
    implementation 'androidx.core:core:1.16.0'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test:runner:1.6.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
}
